graphql:
  playground:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/com_zhuche_server?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

alipay:
  privateKey: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCIGdX9tFe11VGyMJD7hZuxnnhkmk9497G4+MoT08zO+tB+K8SOtivJ+vYsh3qxzNeZuJIIMbw5AfGlAa1PTXWhxvgb3XxozbBIKf9Ub6QmeGh5m/9wJHVFVpoVZGuZlcG3MuTnUhCXC7xqjGHwZp3uBuyTi9ttCmqT7lKbBWRZrV6ZFW4U+FfHG6mLOhphZm611IJ9tczYT7EkDAjh1OPQ2Yyt6xmXPeK6A8WgoREz7nyC1dBo6e3ZtgTfZ/MmBcu2Ik7zIVujgXe1+Gk3cANvIGsGAPFgLr8U6/v8WpoFO8UpC9e53WA76+/nqoh2/Z/oZhmVvwIYKfxWB5h1J6X1AgMBAAECggEAcaMgyXSKx4gVbnKem2QzW1q1q0oskRQ/j/Iqx+NQXoGNE8v3kjEI3txsL0HvcAVY/0DcrXrZbb/xw5Ri4JQMY8d94cZM2jTju11Vk2qj5HskwGVAIqJOSFbG0JXIQbSIyi30cjBTKcrixxPvson704J0hb2AuMq5skqLLmSSJU0i+0A0zNSTrZTywTBFRD5Sf8cngimy8FZBRKyt/fhH9g5vXCegUjPTWZdwJPmCvbZwJVa0zSmy1cvb4PJ+sr746eV9xLzwAK+ajtoSYU8/VnoJfZVZpyk+yAZfkpktOY3/MP2WXWQladu6kf3baOX4TuXgoFnweSsxcL1gI06dAQKBgQDPfPivqE+xTsMZBvwodasKO7ogvo5k3JmCAYCttE7eZ5fGgulNr8IPN0vwpCe3f8Uw9mnuIapVyOcnwdBWYbygepNC9QJzRTXMR+QG0hxaabULatQvaH9QU5R2z9wvSVPkBBQKqbWja7mn3BkwZSLx3/zZs0/XGX+J+MqF2NVMmwKBgQCn7AqN27KtpV4aJN00JTPzTpFdguQWuEzbeNxCucUrhP9tpCminSJsv5k+/vlQdoOBA45+Z73yfc0iXswpUVI/Gi5zF+UsWMIcURbscqSmJmLXHK1lw5LPiQcXeJRGaslfgJqmA05ZV4bYcubDrYst72sfhL4ihZKX9bim97lYrwKBgEXsccqQyDqStoEKr5PbA8cxFarPTSGEjl8XrovbhfDBrI6Ds6gwoQ+LrRXt3EykzImRoWVVBxhd2ji1wkY6Ld1PMa2Q8EB0hIrRd3EtAc0ebproZ5WKe81QPWpE5okxBwqCrVZilwn51dlR/VMn4jztJUMggLmWqDqRE39D8a4dAoGAG11j+uoqnBGu3CPVyIGnjaboGY0TDoDKRZnUiysq7oSl+4AdKNrimUY/+vwiNPKbS5MAzaiqU7Ick9VPAAy4kn/5wdfLCQcN2v979NxZ6Jmo0dVijIrqideSyEhmIXOVjXKvwQ4Y3oZc+zj+UjUd0UaK9n/zXDzYPttUVCFamxECgYAFM9jpZg603tdONJdTdmdXa4izihd0siBhZTsa+dnN5YSQMdkPDT5JlfyhkR/vh186FlIEfW7fhl3AfbOwq7/UuFriawhZ9Z5czR/pOKDwjJ8+YUTNgj1Witt8jOv5Bd6kL6hzYa4f1OYSSZbzlI6NxsgJ0VmAjvSHiz7FMIAqmg=="
  serverUrl: "https://openapi.alipay.com/gateway.do"
  appid: "2021002192682271"
  alipayPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwpEWAL/43cDAsqVaAHS92eCY6B6A0AmCzks9oRzpJQv4XC/xgup0J4fxycuJn8s3VkTahcFRqHFvjsYKME0lTqJslM7a6zT3lCEaWp9aTmaA+H9lE7ZoRlgbU9vcAvVPsx33J1quRg4ML3Zh8IBkaB9T/o762rUuivEAzORTgqB36opXf49CbKK0hXSh6MY9uvfJ0Ren6iRw8wVMRca5cHwVRqV/jBvmtEf2j0oDidtDMxr+G1AlMt+HmgJgmI9Ny0RJhR2z3Wnes4ti+O3MRkQipZARHvfl88jyE0oA+Oo1J9nSOLp37wj5NaaS9KpE7sysz/BRIgKla2ZZ+ltRMwIDAQAB"
