graphql:
  playground:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/com_zhuche_server_test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

alipay:
  privateKey: ""
  serverUrl: "https://openapi.alipay.com/gateway.do"
  appid: ""
  alipayPublicKey: ""

disk:
    qiniu:
        accessKey: ""
        secretKey: ""
        bucket: "zhuche-a1001"
        prefixUrl: "https://zhuche-a1001.qiniu.wuchuheng.com"
